//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmTav_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblClient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblClient()
        {
            this.TblFraction = new HashSet<TblFraction>();
            this.TblReport = new HashSet<TblReport>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public int AgentId { get; set; }
        public System.DateTime DateGenerated { get; set; }
        public Nullable<System.DateTime> DateOfContract { get; set; }
        public Nullable<System.DateTime> DateOfDelivery { get; set; }
        public Nullable<System.DateTime> SupportLap { get; set; }
        public Nullable<long> SupportCost { get; set; }
        public Nullable<System.DateTime> DomainLap { get; set; }
        public Nullable<System.DateTime> HostLap { get; set; }
        public Nullable<System.DateTime> SSLLap { get; set; }
        public string From { get; set; }
        public string PaymentWay { get; set; }
        public Nullable<long> DelayedPenalty { get; set; }
        public string DataWanted { get; set; }
        public Nullable<System.DateTime> DateDataWanted { get; set; }
        public string Proposal { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<long> Price { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string TellNo1 { get; set; }
        public string TellNo2 { get; set; }
        public string StaticTellNo { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string ProjectName { get; set; }
        public string IdentificationNo { get; set; }
        public string Website { get; set; }
    
        public virtual TblAgent TblAgent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFraction> TblFraction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblReport> TblReport { get; set; }
    }
}
