//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmTav_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMoney
    {
        public int id { get; set; }
        public long Amount { get; set; }
        public string Description { get; set; }
        public string Date { get; set; }
        public string DatePass { get; set; }
    }
}
