//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmTav_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblReminder
    {
        public int id { get; set; }
        public string Title { get; set; }
        public System.DateTime Time { get; set; }
        public int AgentId { get; set; }
        public bool IsReminded { get; set; }
    
        public virtual TblAgent TblAgent { get; set; }
    }
}
