//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmTav_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblReport
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string Desc { get; set; }
        public string Date { get; set; }
        public int ClientId { get; set; }
    
        public virtual TblClient TblClient { get; set; }
    }
}
